# Generated by Django 4.2.7 on 2025-08-09 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "department_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Department"),
                            ("administrative", "Administrative Department"),
                        ],
                        default="academic",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_departments",
                        to="staff.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.CharField(max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("date_of_birth", models.DateField()),
                ("address", models.TextField()),
                ("next_of_kin_name", models.CharField(max_length=200)),
                ("next_of_kin_relationship", models.CharField(max_length=100)),
                ("next_of_kin_phone", models.CharField(max_length=15)),
                ("next_of_kin_address", models.TextField()),
                ("position", models.CharField(max_length=100)),
                (
                    "staff_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Staff"),
                            ("administrative", "Administrative Staff"),
                            ("support", "Support Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "staff_category",
                    models.CharField(
                        choices=[
                            ("senior", "Senior Staff"),
                            ("senior_supporting", "Senior Supporting Staff"),
                            ("junior", "Junior Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "staff_grade",
                    models.CharField(
                        choices=[
                            ("1", "Scale 1"),
                            ("2", "Scale 2"),
                            ("3", "Scale 3"),
                            ("4", "Scale 4"),
                            ("5", "Scale 5"),
                            ("6", "Scale 6"),
                            ("7", "Scale 7"),
                            ("8.1", "Scale 8.1"),
                            ("8.2", "Scale 8.2"),
                            ("8.3", "Scale 8.3"),
                            ("8.4", "Scale 8.4"),
                            ("8.5", "Scale 8.5"),
                            ("8.6", "Scale 8.6"),
                            ("8.7", "Scale 8.7"),
                            ("8.8", "Scale 8.8"),
                            ("8.9", "Scale 8.9"),
                            ("8.10", "Scale 8.10"),
                            ("j1", "Junior Scale 1"),
                            ("j2", "Junior Scale 2"),
                            ("j3", "Junior Scale 3"),
                            ("j4", "Junior Scale 4"),
                            ("j5", "Junior Scale 5"),
                            ("j6", "Junior Scale 6"),
                            ("j7", "Junior Scale 7"),
                            ("j8", "Junior Scale 8"),
                        ],
                        max_length=10,
                    ),
                ),
                ("hire_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("retired", "Retired"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("bank_account_number", models.CharField(max_length=50)),
                ("bank_sort_code", models.CharField(blank=True, max_length=20)),
                ("nassit_number", models.CharField(max_length=50, unique=True)),
                ("highest_qualification", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("graduation_year", models.IntegerField()),
                ("other_qualifications", models.TextField(blank=True)),
                (
                    "publications",
                    models.TextField(
                        blank=True,
                        help_text="List of publications, research papers, books, etc.",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="staff_photos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("leave_applied", "Leave Applied"),
                            ("leave_approved", "Leave Approved"),
                            ("leave_rejected", "Leave Rejected"),
                            ("promotion_applied", "Promotion Applied"),
                            ("promotion_approved", "Promotion Approved"),
                            ("promotion_rejected", "Promotion Rejected"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("content_type", models.CharField(max_length=50)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff_affected",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="staff.staff"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Retirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("retirement_date", models.DateField()),
                (
                    "retirement_type",
                    models.CharField(
                        choices=[
                            ("voluntary", "Voluntary"),
                            ("mandatory", "Mandatory"),
                            ("early", "Early Retirement"),
                        ],
                        max_length=50,
                    ),
                ),
                ("benefits_info", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("notification_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="staff.staff"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_position", models.CharField(max_length=100)),
                ("new_position", models.CharField(max_length=100)),
                ("old_grade", models.CharField(max_length=10)),
                ("new_grade", models.CharField(max_length=10)),
                ("effective_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_promotions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_promotions",
                        to="staff.department",
                    ),
                ),
                (
                    "old_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="old_promotions",
                        to="staff.department",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="staff.staff"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("leave_applied", "Leave Applied"),
                            ("leave_approved", "Leave Approved"),
                            ("leave_rejected", "Leave Rejected"),
                            ("promotion_applied", "Promotion Applied"),
                            ("promotion_approved", "Promotion Approved"),
                            ("promotion_rejected", "Promotion Rejected"),
                            ("retirement_processed", "Retirement Processed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content_type", models.CharField(blank=True, max_length=50)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Leave"),
                            ("sick", "Sick Leave"),
                            ("maternity", "Maternity Leave"),
                            ("paternity", "Paternity Leave"),
                            ("study", "Study Leave"),
                            ("emergency", "Emergency Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("days_requested", models.IntegerField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("applied_date", models.DateTimeField(auto_now_add=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="staff.staff"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HRMO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="staff.staff"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "HRMO",
                "verbose_name_plural": "HRMOs",
            },
        ),
        migrations.AddField(
            model_name="department",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="staff.school",
            ),
        ),
        migrations.CreateModel(
            name="Bereavement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deceased_name", models.CharField(max_length=200)),
                ("relationship", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("days_granted", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("approved", "Approved"), ("pending", "Pending")],
                        default="approved",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="staff.staff"
                    ),
                ),
            ],
        ),
    ]
