# Generated by Django 4.2.7 on 2025-08-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="leadership_role",
            field=models.CharField(
                choices=[
                    ("none", "No Leadership Role"),
                    ("vice_chancellor", "Vice Chancellor"),
                    ("dvc_academic", "Deputy Vice Chancellor (Academic)"),
                    ("dvc_admin", "Deputy Vice Chancellor (Administration)"),
                    ("registrar", "Registrar"),
                    ("bursar", "Bursar"),
                    ("dean", "Dean of School"),
                    ("hod", "Head of Department"),
                    ("director", "Director"),
                    ("coordinator", "Coordinator"),
                    ("unit_head", "Unit Head"),
                    ("librarian", "Chief Librarian"),
                    ("security_head", "Head of Security"),
                    ("maintenance_head", "Head of Maintenance"),
                ],
                default="none",
                max_length=30,
            ),
        ),
    ]
