# Generated by Django 4.2.7 on 2025-08-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0002_staff_leadership_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "retirement_age",
                    models.IntegerField(
                        default=65, help_text="Retirement age in years"
                    ),
                ),
                (
                    "retirement_notification_months",
                    models.IntegerField(
                        default=6,
                        help_text="Months before retirement to send notifications",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
