# Generated by Django 4.2.7 on 2025-08-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0003_systemsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("senior", "Senior Staff"),
                            ("junior", "Junior Staff"),
                            ("supporting", "Supporting Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "code"],
            },
        ),
    ]
