# Generated by Django 4.2.7 on 2025-08-12 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("staff", "0004_staffgrade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("announcement", "General Announcement"),
                            ("letter", "Official Letter"),
                            ("notice", "Notice"),
                            ("memo", "Memorandum"),
                        ],
                        default="announcement",
                        max_length=20,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "All Staff"),
                            ("academic", "Academic Staff"),
                            ("administrative", "Administrative Staff"),
                            ("support", "Support Staff"),
                            ("senior", "Senior Staff"),
                            ("junior", "Junior Staff"),
                            ("leadership", "Leadership Roles"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "send_email",
                    models.BooleanField(
                        default=False, help_text="Send via email to targeted staff"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specific_departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to target all departments",
                        to="staff.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
