# Generated by Django 4.2.7 on 2025-08-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0005_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="contract_renewal_notification_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staff",
            name="contract_start_date",
            field=models.DateField(
                blank=True, help_text="For contract and associate staff", null=True
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                    ("associate", "Associate"),
                    ("beyond_retirement", "Employment Beyond Retirement"),
                ],
                default="full_time",
                max_length=20,
            ),
        ),
    ]
