# Generated by Django 4.2.7 on 2025-08-12 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("staff", "0006_add_employment_type_and_contract_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="supervisor_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervisor_approved_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="supervisor_approved_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotion",
            name="supervisor_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervisor_approved_promotions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="supervisor_approved_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_staff",
                to="staff.staff",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_approved_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Supervisor Approval"),
                    ("supervisor_approved", "Supervisor Approved"),
                    ("approved", "HR Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_approved_promotions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Supervisor Approval"),
                    ("supervisor_approved", "Supervisor Approved"),
                    ("approved", "HR Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
