# Generated by Django 4.2.7 on 2025-08-13 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("staff", "0008_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="BenefitPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "benefit_type",
                    models.CharField(
                        choices=[
                            ("health", "Health Insurance"),
                            ("life", "Life Insurance"),
                            ("pension", "Pension Plan"),
                            ("education", "Education Allowance"),
                            ("transport", "Transport Subsidy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "employer_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "employee_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_mandatory", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "staff_category",
                    models.CharField(
                        choices=[
                            ("senior", "Senior Staff"),
                            ("senior_supporting", "Senior Supporting Staff"),
                            ("junior", "Junior Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "staff_grade",
                    models.CharField(
                        choices=[
                            ("1", "Scale 1"),
                            ("2", "Scale 2"),
                            ("3", "Scale 3"),
                            ("4", "Scale 4"),
                            ("5", "Scale 5"),
                            ("6", "Scale 6"),
                            ("7", "Scale 7"),
                            ("8.1", "Scale 8.1"),
                            ("8.2", "Scale 8.2"),
                            ("8.3", "Scale 8.3"),
                            ("8.4", "Scale 8.4"),
                            ("8.5", "Scale 8.5"),
                            ("8.6", "Scale 8.6"),
                            ("8.7", "Scale 8.7"),
                            ("8.8", "Scale 8.8"),
                            ("8.9", "Scale 8.9"),
                            ("8.10", "Scale 8.10"),
                            ("j1", "Junior Scale 1"),
                            ("j2", "Junior Scale 2"),
                            ("j3", "Junior Scale 3"),
                            ("j4", "Junior Scale 4"),
                            ("j5", "Junior Scale 5"),
                            ("j6", "Junior Scale 6"),
                            ("j7", "Junior Scale 7"),
                            ("j8", "Junior Scale 8"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("associate", "Associate"),
                            ("beyond_retirement", "Employment Beyond Retirement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "housing_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "transport_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "medical_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {
                    ("staff_category", "staff_grade", "employment_type")
                },
            },
        ),
        migrations.CreateModel(
            name="LoanRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("salary_advance", "Salary Advance"),
                            ("emergency", "Emergency Loan"),
                            ("housing", "Housing Loan"),
                            ("education", "Education Loan"),
                            ("other", "Other Loan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "interest_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("repayment_months", models.IntegerField()),
                (
                    "monthly_deduction",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("application_date", models.DateField(auto_now_add=True)),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("start_deduction_date", models.DateField(blank=True, null=True)),
                ("end_deduction_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="staff.staff"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrollment_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employee_contribution_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "benefit_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.benefitplan",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="staff.staff"
                    ),
                ),
            ],
            options={
                "unique_together": {("staff", "benefit_plan")},
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "housing_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "transport_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "medical_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "overtime_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "income_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "nassit_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "loan_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("unpaid_leave_days", models.IntegerField(default=0)),
                (
                    "unpaid_leave_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("gross_pay", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("net_pay", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payslips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payroll_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.payrollperiod",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="staff.staff"
                    ),
                ),
            ],
            options={
                "ordering": ["-payroll_period__start_date"],
                "unique_together": {("staff", "payroll_period")},
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annual_leave_balance", models.IntegerField(default=21)),
                ("sick_leave_balance", models.IntegerField(default=10)),
                ("maternity_leave_balance", models.IntegerField(default=90)),
                ("paternity_leave_balance", models.IntegerField(default=7)),
                ("study_leave_balance", models.IntegerField(default=0)),
                ("emergency_leave_balance", models.IntegerField(default=3)),
                ("annual_leave_carried_over", models.IntegerField(default=0)),
                ("year", models.IntegerField(default=2025)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="staff.staff"
                    ),
                ),
            ],
            options={
                "unique_together": {("staff", "year")},
            },
        ),
    ]
